apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      variant: a
  template:
    metadata:
      labels:
        app: aceest
        variant: a
    spec:
      containers:
      - name: aceest
        image: <dockerhub-user>/aceest-fitness:va
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      variant: b
  template:
    metadata:
      labels:
        app: aceest
        variant: b
    spec:
      containers:
      - name: aceest
        image: <dockerhub-user>/aceest-fitness:vb
        ports:
        - containerPort: 5000
