apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      version: blue
  template:
    metadata:
      labels:
        app: aceest
        version: blue
    spec:
      containers:
      - name: aceest
        image: <dockerhub-user>/aceest-fitness:stable
        ports:
        - containerPort: 5000
