apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
      - name: aceest
        image: <dockerhub-user>/aceest-fitness:latest
        ports:
        - containerPort: 5000
