apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-shadow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      role: shadow
  template:
    metadata:
      labels:
        app: aceest
        role: shadow
    spec:
      containers:
      - name: aceest
        image: <dockerhub-user>/aceest-fitness:shadow
        ports:
        - containerPort: 5000
